### ISSUE TITLE
Can't add more than a word in the "Biography" Section

### ISSUE THREAD

**Issue by tumma** [philipempl/modern-latex-cv#2]
Under Biography section in main.tex in Latex website, I am getting error if i replace "\Blindtext[1]" with more than a word. And I couldn't find where this Blindtext[1] function was written. Please support at the earliest.

**Comment by philipempl** [comment]
Hi, tumma,
you can find the blindtext section at line 542. If you would like to write anything into that section, you need to ensure writing into \cvtext{}, and you may delete the Blindtext. In general, blindtext is a CTAN package and was not written by me. I just added it to ensure a straightforward template for you.
Hope this clarifies your problems.
Have a nice day.
Philip

**Comment by philipempl** [comment]
I am going to mark this issue as resolved.
