### ISSUE TITLE
Well fitting Cover Leter

### ISSUE THREAD

**Issue by r-neuschulz** [philipempl/modern-latex-cv#3]
Hi Philip,

thanks for compiling such a nice-looking and well-rounded LaTeX CV! It is much appreciated!

I assume you use it for your own applications, too? Do you happen to know of any well-fitting cover letter design?

Cheers
Richard

**Comment by philipempl** [comment]
Hi Richard, 

i am glad that you appreciate my template. Of cource i can upload my cover letter.

Best regards,
Philip
