### ISSUE TITLE
Add a licence file

### ISSUE THREAD

**Issue by SebastianoF** [philipempl/modern-latex-cv#6]
By default if no licence is found, it is implicitly stated that no permission to use the code is given to anyone.

<https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license>

Thank you!

**Comment by Cs137** [comment]
https://github.com/philipempl/modern-latex-cv/blob/02c1e9139698cfc057be3c16187a1750e21c5742/cv.tex#L3

**Comment by SebastianoF** [comment]
I saw that line, thanks, I meant a file. As specified for example in:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
Thanks again.

**Comment by philipempl** [comment]
Many thanks to @SebastianoF for the hint. I have added a license file. Have fun using the code.
